name: drupal8
recipe: drupal8
config:
  php: '7.1'
  via: nginx
  webroot: web
  drush: stable
  drupal: true
  database: mariadb:latest
  xdebug: true

services:
  database:
    portforward: 3307

events:
  post-start:
  - appserver: cd $LANDO_MOUNT && composer dump-autoload -o

# drush si --db-url=mysql://drupal8:drupal8@database:3306/drupal8 --account-pass=12345