<?php

/**
 * @file
 * Contains weather.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function weather_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the weather module.
    case 'help.page.weather':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Weather Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function weather_theme() {
  return [
    'weather' => [
      'variables' => [
        'location' => '',
        'temperature' => '',
        'weather_description' => '',
        'icon' => '',
        'attributes' => []
      ],
    ],
  ];
}

/**
 * Implements template_preprocess_ELEMENT_ID()
 * @param $variables
 */
function template_preprocess_weather(&$variables) {
  // Add Caching Context
  $variables['cache'] = [
    'contexts' => ['ip'],
    'max-age' => 3600
  ];
}